Prepare packages for publishing
balancer-labs/balancer-v2-monorepo pull request #590
Opened 2021-05-29 00:57 UTC by nventuro

This prepares most Solidity packages for them to be released. 

It adds the `files` field to the different `package.json` files, as well as minimal readmes for each of them so there is _something_ to show on npm. I've updated the repository links to `balancer-v2-monorepo`, in preparation for the renaming of this repository.

It also sets up dependencies between packages instead of dev-dependencies, meaning a user that e.g. installs `pool-utils` will also get `vault` and `solidity-utils` automatically. You will notice that the dependencies don't list semver ranges but rather use the `workspace:*` syntax: when running `yarn pack` or `yarn npm publish` these are automatically updated to the current version.

I've bumped all packages we intend to publish immediately (deployments, vault, pool-weighted, pool-utils, solidity-utils) to 1.0.0: pool-stable and asset-manager-utils remain in 0.1.0 meaning they are not quite ready to have an initial version out.

I've additionally installed the `yarn version` plugin, which we can use to track which packages are pending a version bump as we make commits to the repository. You can read more about this plugin [here](https://yarnpkg.com/features/release-workflow).

2021-05-29 20:17 UTC, EndymionJkb requested changes

2021-05-29 20:17 UTC, EndymionJkb commented on pkg/pool-weighted/README.md
> +This package contains the source code of Balancer V2 Weighted Pools, that is, Pools that swap tokens by enforcing a Constant Weighted Product invariant.
```suggestion
This package contains the source code for Balancer V2 Weighted Pools, that is, Pools that swap tokens by enforcing a Constant Weighted Product invariant.
```

2021-05-29 20:17 UTC, EndymionJkb commented on pkg/solidity-utils/README.md
> +This package contains Solidity utilities and libraries used when developing Balancer V2 contracts. Many design decisions and trade-offs have been made in the context of Balancer V2's requirements and
```suggestion
This package contains Solidity utilities and libraries used when developing Balancer V2 contracts. Many design decisions and trade-offs have been made in the context of Balancer V2's requirements and constraints (such as reduced bytecode size), which may make these libraries unsuitable for other projects.
```

2021-05-29 20:17 UTC, EndymionJkb commented on pkg/vault/README.md
> +The [Vault interface](./contracts/interfaces/IVault.sol) itself is required for multiple tasks, including swaps, joins and exits, but some scenario require using a few additional ones. Particularly u
```suggestion
The [Vault interface](./contracts/interfaces/IVault.sol) itself is required for multiple tasks, including swaps, joins and exits, but some scenarios require functionality provided through other contracts. Particularly useful interfaces include:
```

2021-05-29 20:17 UTC, EndymionJkb commented on pkg/vault/README.md
> +The main purpose if this package is to provide the Solidity interfaces of core components, which are found in the [`/contracts/interfaces`](./contracts/interfaces] directory. The Vault contract itsel
```suggestion
The main purpose of this package is to provide the Solidity interfaces of core components, which are found in the [`/contracts/interfaces`](./contracts/interfaces] directory. The Vault contract itself is also useful for testing.
```

2021-05-31 19:01 UTC, nventuro commented
This should be now ready to publish.

2021-05-31 19:10 UTC, EndymionJkb commented on pkg/pool-weighted/README.md
> +      uint256[] memory results = oracle.getTimeWeightedAverage(queries);
Should this check that the oracle has been fully initialized? (Or at least have a comment that it's only guaranteed to work then?)

2021-05-31 20:04 UTC, EndymionJkb requested changes

2021-05-31 20:04 UTC, EndymionJkb commented on pkg/pool-weighted/README.md
> +This package can be used in multiple ways, including interacting with already deployed Pools, performing local testing, or even create new Pool types that also use the Constant Weighted Product invar
```suggestion
This package can be used in multiple ways, including interacting with already deployed Pools, performing local testing, or even creating new Pool types that also use the Constant Weighted Product invariant.
```

2021-05-31 20:07 UTC, merged